[theme]
# Primary accent color for interactive elements.
primaryColor = "#00FF7"

# Background color for the main content area.
backgroundColor = "#606C38"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#283618"

# Color used for almost all text.
textColor = "##FAF6F5"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "monospace"